
# container 
container: "docker://ghcr.io/retogerber/imc_to_ims_workflow:analysis_1.0"

# name of csv file containing sample information
sample_metadata: "config/sample_metadata.csv"

# channel names of IMC for aggregation for registration 
IMC_channels_for_aggr: ["E-cadherin","ST6GAL1","Collagen-1","HepPar1","Seg1","Seg2","Seg3"]


